# Code compares files HIVPrevCasc_Indiv_runI_tYYYY.csv files generated by function write_prevention_cascade_barriers() in debug.c.


rm(list=ls())

run <- 3
data.t1 <- read.csv(paste0("../src/HIVPrevCasc_Indiv_run",as.character(run),"_t2018.csv"),header=T,sep=",")
data.t2 <- read.csv(paste0("../src/HIVPrevCasc_Indiv_run",as.character(run),"_t2020.csv"),header=T,sep=",")
data.t3 <- read.csv(paste0("../src/HIVPrevCasc_Indiv_run",as.character(run),"_t2022.csv"),header=T,sep=",")



df.circ <- function(circ,sex){
    circ[circ %in% 0 & sex %in% "M"] <- "Uncircumcised"
    circ[circ %in% 0 & sex %in% "F"] <- NA
    circ[circ %in% 2] <- "VMMC"
    circ[circ %in% 4] <- "Traditional MC"
    return(circ)
}


# Make results more readable:
data.t1$Circ <- df.circ(data.t1$Circ_status,data.t1$Sex)
data.t2$Circ <- df.circ(data.t2$Circ_status,data.t2$Sex)
data.t3$Circ <- df.circ(data.t3$Circ_status,data.t3$Sex)


data.all <- merge(data.t1,data.t2,by="id")



data.all <- data.all[,!names(data.all) %in% c("Circ_status.x", "Circ_status.y", "Sex.y")]

names(data.all)[names(data.all)=="Sex.x"] <- "Sex"

data.all <- merge(data.all,data.t3,by="id")

names(data.all)[names(data.all)=="p_will_use_PrEP"] <- "p_will_use_PrEP.z"
names(data.all)[names(data.all)=="p_will_get_VMMC"] <- "p_will_get_VMMC.z"
names(data.all)[names(data.all)=="Circ"] <- "Circ.z"
names(data.all)[names(data.all)=="Age"] <- "Age.z"
names(data.all)[names(data.all)=="n_lifetime_partners"] <- "n_lifetime_partners.z"
names(data.all)[names(data.all)=="PrEP_status"] <- "PrEP_status.z"
names(data.all)[names(data.all)=="prop_partners_LT_cond"] <- "prop_partners_LT_cond.z"
names(data.all)[names(data.all)=="prop_partners_casual_cond"] <- "prop_partners_casual_cond.z"
names(data.all)[names(data.all)=="p_want_to_use_condom_long_term_partner"] <- "p_want_to_use_condom_long_term_partner.z"
names(data.all)[names(data.all)=="p_want_to_use_condom_casual_partner"] <- "p_want_to_use_condom_casual_partner.z"

# Remove the extras from data.t3:
data.all <- data.all[,!names(data.all) %in% c("Circ_status","Sex.y")]


 tabulate.data <- function(outcome.t1,outcome.t2,restrictions)
{
    
    table(outcome.t1[restrictions],outcome.t2[restrictions])

}

check.data <- function(outcome.t1,outcome.t2,restrictions,value.t1,value.t2)
{
    
    all(outcome.t1[restrictions]==value.t1) & all(outcome.t2[restrictions]==value.t2)

}








####################################################
###PrEP checks:                                    #
####################################################


# Should be 0->0
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(13,14) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% 0,0,0) & 
# Should be 0->0.001
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(13,14) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.001) &
# Should be 0->0
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(13,14) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% 0, 0, 0) &
# Should be 0->0.003
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(13,14) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.003) &
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y, data.all$n_lifetime_partners.y %in% 0,0,0) &
# Should be 0.001->0.001
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(15,27) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.001,0.001) &
# Should be 0->0.001
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(15,27) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.001) &
# Should be 0.001->0.002
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(28,29) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.001,0.002) &
# Should be 0->0.002
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(28,29) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.002) &
# ERROR: Should be 0.002->0.002
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(30,52) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.002,0.002) &
#tabulate.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(30,52) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% seq(1,1000))
# Should be 0->0.002
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(30,52) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.002) &
# Should be 0.002->0
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(53,54) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.002,0) &
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(55,500) & data.all$Sex %in% "M",0,0)

# Make sure the above is TRUE.


###
                                        # Now women:

# Should be 0.003->0.003
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(15,22) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.003,0.003) &
# Should be 0->0.003
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(15,22) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.003) &
# Should be 0.003->0.004
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(23,24) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.003,0.004) &
# Should be 0->0.004
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(23,24) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.004) &
# ERROR: Should be 0.004->0.004
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(25,52) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.004,0.004) &
# Should be 0->0.004
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(25,52) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% 0 & data.all$n_lifetime_partners.y %in% seq(1,1000),0,0.004) &
# Should be 0.004->0
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% c(53,54) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.x %in% seq(1,1000),0.004,0) &
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.x,data.all$p_will_use_PrEP.y,data.all$Age.x %in% seq(55,500) & data.all$Sex %in% "F",0,0) 



###################
# Now intervention:
##################
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z, data.all$n_lifetime_partners.z %in% 0,0,0) &
# Should be 0.001->0.13
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(15,27) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.001,0.13) &
# Should be 0->0.13
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(15,27) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.13) &
# Should be 0.001->0.14
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(28,29) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.001,0.14) &
# Should be 0->0.14
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(28,29) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.14) &
# ERROR: Should be 0.002->0.14
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(30,52) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.002,0.14) &
# Should be 0->0.14
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(30,52) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.14) &
# Should be 0.002->0
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(53,54) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.002,0) &
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(55,500) & data.all$Sex %in% "M",0,0)

###
                                        # Now women:

# Should be 0.003->0.15
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(15,22) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.003,0.15) &
# Should be 0->0.15
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(15,22) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.15) & 
# Should be 0.003->0.16
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(23,24) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.003,0.16) &
# Should be 0->0.16
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(23,24) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.16) &
# ERROR: Should be 0.004->0.16
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(25,52) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.004,0.16) &
# Should be 0->0.16
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(25,52) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% 0 & data.all$n_lifetime_partners.z %in% seq(1,1000),0,0.16) &
# Should be 0.004->0
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% c(53,54) & data.all$Sex %in% "F" & data.all$n_lifetime_partners.y %in% seq(1,1000),0.004,0) &
# Should be 0->0:
check.data(data.all$p_will_use_PrEP.y,data.all$p_will_use_PrEP.z,data.all$Age.y %in% seq(55,500) & data.all$Sex %in% "F",0,0) 



####################################################
###VMMC checks:                                    #
####################################################


# Should be 0->0.05
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% c(13,14) & data.all$Sex %in% "M",0,0.05) &
# Should be 0.05->0.05
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% seq(15,27) & data.all$Sex %in% "M",0.05,0.05) &
# Should be 0.05->0.02
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% c(28,29) & data.all$Sex %in% "M",0.05,0.02) &
# ERROR: Should be 0.02->0.02
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% seq(30,52) & data.all$Sex %in% "M",0.02,0.02) &
# Should be 0.02->0
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% c(53,54) & data.all$Sex %in% "M",0.02,0) &
# Should be 0->0:
check.data(data.all$p_will_get_VMMC.x,data.all$p_will_get_VMMC.y,data.all$Age.x %in% seq(55,500) & data.all$Sex %in% "M",0,0)


############################
# VMMC intervention:

# Should be 0->0.11
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% c(13,14) & data.all$Sex %in% "M",0,0.11) &
# Should be 0.05->0.11
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% seq(15,27) & data.all$Sex %in% "M",0.05,0.11) &
# Should be 0.05->0.12
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% c(28,29) & data.all$Sex %in% "M",0.05,0.12) &
# ERROR: Should be 0.02->0.12
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% seq(30,52) & data.all$Sex %in% "M",0.02,0.12) &
# Should be 0.02->0
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% c(53,54) & data.all$Sex %in% "M",0.02,0) &
# Should be 0->0:
check.data(data.all$p_will_get_VMMC.y,data.all$p_will_get_VMMC.z,data.all$Age.y %in% seq(55,500) & data.all$Sex %in% "M",0,0)



#####################################################
# Condom use:
#####################################################

#data.all$id[data.all$Age.x %in% c(13,14) & data.all$Sex %in% "M" & data.all$n_lifetime_partners.y %in% seq(1,1000) & data.all$p_will_use_PrEP.x==0 & data.all$p_will_use_PrEP.y==0]
#Need to find out why these epople don't change probability of getting PrEP once aged 15:
#[1] 2019

###### Long-term partners:

# Should be 0.009->0.009
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(13,27) & data.all$Sex %in% "M",0.009,0.009) &
# Should be 0.009->0.010
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(28,29) & data.all$Sex %in% "M",0.009,0.010) &
# Should be 0.010->0.010
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(30,500) & data.all$Sex %in% "M",0.010,0.010) &
# Should be 0.011->0.011
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(13,22) & data.all$Sex %in% "F",0.011,0.011) &
# Should be 0.011->0.012
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(23,24) & data.all$Sex %in% "F",0.011,0.012) &
# Should be 0.012->0.012
check.data(data.all$p_want_to_use_condom_long_term_partner.x,data.all$p_want_to_use_condom_long_term_partner.y,data.all$Age.x %in% seq(25,500) & data.all$Sex %in% "F",0.012,0.012)


#######################
# intervention:
# Should be 0.009->0.21
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(13,27) & data.all$Sex %in% "M",0.009,0.21) &
# Should be 0.009->0.22
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(28,29) & data.all$Sex %in% "M",0.009,0.22) &
# Should be 0.010->0.22
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(30,500) & data.all$Sex %in% "M",0.010,0.22) &
# Should be 0.011->0.23
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(13,22) & data.all$Sex %in% "F",0.011,0.23) &
# Should be 0.011->0.24
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(23,24) & data.all$Sex %in% "F",0.011,0.24) &
# Should be 0.012->0.24
check.data(data.all$p_want_to_use_condom_long_term_partner.y,data.all$p_want_to_use_condom_long_term_partner.z,data.all$Age.y %in% seq(25,500) & data.all$Sex %in% "F",0.012,0.24)




# Casual:
# Should be 0.005->0.005
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(13,27) & data.all$Sex %in% "M",0.005,0.005) &
# Should be 0.005->0.006
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(28,29) & data.all$Sex %in% "M",0.005,0.006) &
# Should be 0.006->0.006
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(30,500) & data.all$Sex %in% "M",0.006,0.006) &
# Should be 0.007->0.007
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(13,22) & data.all$Sex %in% "F",0.007,0.007) &
# Should be 0.007->0.008
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(23,24) & data.all$Sex %in% "F",0.007,0.008) &
# Should be 0.008->0.008
check.data(data.all$p_want_to_use_condom_casual_partner.x,data.all$p_want_to_use_condom_casual_partner.y,data.all$Age.x %in% seq(25,500) & data.all$Sex %in% "F",0.008,0.008)

#intervention:
# Should be 0.005->0.17
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(13,27) & data.all$Sex %in% "M",0.005,0.17) &
# Should be 0.005->0.18
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(28,29) & data.all$Sex %in% "M",0.005,0.18) &
# Should be 0.006->0.18
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(30,500) & data.all$Sex %in% "M",0.006,0.18) &
# Should be 0.007->0.19
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(13,22) & data.all$Sex %in% "F",0.007,0.19) &
# Should be 0.007->0.20
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(23,24) & data.all$Sex %in% "F",0.007,0.20) &
# Should be 0.008->0.20
check.data(data.all$p_want_to_use_condom_casual_partner.y,data.all$p_want_to_use_condom_casual_partner.z,data.all$Age.y %in% seq(25,500) & data.all$Sex %in% "F",0.008,0.20)

