# Take a file prop_infections_heatmap.csv (generated by impact_outputs_allruns.py) and make a heatmap plot using ggplot2.



########################################
# Using ggplot2:
########################################
rm(list=ls())
library(ggplot2)
library(tidyr)
library(RColorBrewer)


low.col <- brewer.pal(9,"Greens")[1]
high.col <- brewer.pal(9,"Greens")[9]

# Based on https://jcoliver.github.io/learn-r/006-heatmaps.html

tidy.dataset <- function(m,name.impact)
{
    # Rename columns of dataset:
    names(m) <- c("Tool","Barriers","Population",name.impact)
    levels(m$Tool)[levels(m$Tool)=="cond"] <- "Condom"
    m$Tool <- factor(m$Tool, levels=c("PrEP","VMMC","Condom"))
    levels(m$Barriers) <- c("None","Access","Effective use","Motivation","All lowered")
    m$Barriers <- factor(m$Barriers, levels=c("None","Motivation","Access","Effective use","All lowered"))
    return(m)
}

stop.negative.impact <- function(m)
{
    m[,4] <- pmax(m[,4],0)
    return(m)
}

m.prop.inf <- read.csv("prop_infections_heatmap.csv",sep=",",header=FALSE)
m.prop.inf <- tidy.dataset(m.prop.inf,"Prop.Averted")
# Use this to force impacts to be >=0 (0 if negative).
m.prop.inf <- stop.negative.impact(m.prop.inf)
# Rescale to % averted:
m.prop.inf$Prop.Averted <- 100*m.prop.inf$Prop.Averted
m.prop.inf$Population <- factor(m.prop.inf$Population, levels = c("F15_24","F25_54","M15_29","M30_54","all_priority_pops"))

m.N.inf <- read.csv("N_infections_heatmap.csv",sep=",",header=FALSE)
m.N.inf <- tidy.dataset(m.N.inf,"N.Averted")
# Use this to force impacts to be >=0 (0 if negative).
m.N.inf <- stop.negative.impact(m.N.inf)

m.incidence <- read.csv("Incidence_heatmap.csv",sep=",",header=FALSE)
m.incidence <- tidy.dataset(m.incidence,"Incidence")
m.incidence$Incidence <- 100*m.incidence$Incidence




#names(m.prop.inf) <- c("Tool","Barriers","Population","Prop.Averted")

#m.prop.inf$Tool <- factor(m$Tool, levels=c("PrEP","VMMC","Condom"))
#levels(m.prop.inf$Barriers) <- c("None","Access","Effective use","Motivation","All lowered")
#m.prop.inf$Barriers <- factor(m.prop.inf$Barriers, levels=c("None","Motivation","Access","Effective use","All lowered"))
#low.col <- "#FFFFFF"
#high.col <- "#012345"
#heat.colors(100)[100]


draw.heatmap <- function(m,pop.names,outcome.name,graph.title)
{
    this.heatmap <- ggplot(data = m, mapping = aes(x = Population,
                                                   y = Barriers,
                                                   fill = m[,4])) +
        geom_tile() +
        xlab(label = "Population") +
        ylab(label="Barrier lowered") +
        facet_grid(~ Tool, scales = "free_x", space = "free_x")+
        ggtitle(graph.title)+
        theme(text = element_text(size=14)) + 
        scale_fill_gradient(name = outcome.name,
                            low = low.col,
                            high = high.col) +
        #scale_x_discrete(labels=c(pop.names,c("A","B","C"),pop.names) + # Relabel x axis.
        scale_y_discrete(limits = rev(levels(as.factor(m$Barriers)))) # reverse the barrier ordering (so all barriers at the top).
    
                                        # Now draw the heatmap:
    return(this.heatmap)
}    


draw.heatmap.truncated <- function(m,pop.names,outcome.name,graph.title)
{
    this.heatmap <- ggplot(data = m, mapping = aes(x = Population,
                                                   y = Barriers,
                                                   fill = m[,4])) +
        geom_tile() +
        xlab(label = "Population") +
        ylab(label="Barrier lowered") +
        facet_grid(~ Tool, scales = "free_x", space = "free_x")+
        ggtitle(graph.title)+
        theme(text = element_text(size=14)) + 
        scale_fill_gradient(labels = c("0", "5", "10", "15", "20", "25", ">=30"), breaks=seq(0,30,5), name = outcome.name,
                            low = low.col,
                            high = high.col) +
        #scale_x_discrete(labels=c(pop.names,c("A","B","C"),pop.names) + # Relabel x axis.
        scale_y_discrete(limits = rev(levels(as.factor(m$Barriers)))) # reverse the barrier ordering (so all barriers at the top).
    
                                        # Now draw the heatmap:
    return(this.heatmap)
}    





pops <- c("15-24F","25-54F","15-29M","30-54M","All priority pops")

propinf.heatmap <- draw.heatmap(m.prop.inf,pops,"% reduction","% reduction in infections by removing barriers")
pdf("PropInfHeatmap.pdf",width=16,height=10)
propinf.heatmap
dev.off()


# Version of the heatmap where we truncated at 30% impact (so that the all/all scenario doesn't dominate)
m.prop.inf.trunc <- m.prop.inf
m.prop.inf.trunc$Prop.Averted <- pmin(m.prop.inf.trunc$Prop.Averted,30)
propinf.heatmap.trunc <- draw.heatmap.truncated(m.prop.inf.trunc,pops,"% reduction","% reduction in infections by removing barriers")
pdf("PropInfHeatmap_truncated.pdf",width=16,height=10)
propinf.heatmap.trunc
dev.off()



Ninf.heatmap <- draw.heatmap(m.N.inf,pops,"Reduction","Reduction in number of infections by removing barriers")
pdf("NInfHeatmap.pdf",width=12,height=10)
Ninf.heatmap
dev.off()

incidence.heatmap <- draw.heatmap(m.incidence,pops,"Incidence (%)","Incidence in 2030")
pdf("IncidenceHeatmap.pdf",width=12,height=10)
incidence.heatmap
dev.off()


########################################
# Using base graphics:
########################################

#barrier.list <- c("allbarriers","increase_motivation","increase_access","increase_effuse","remove_barriers")

#m.PrEP <- read.csv("prop_infections_heatmap_PrEP.csv",sep=",",header=FALSE)
#heatmap(m.PrEP,Rowv=NA , Colv=NA, labRow=barrier.list, labCol=c("M15_29","M30_54","F15_24","F25_54"),xlab="Population",ylab="Barrier")


prop.heatmap <- ggplot(data = m, mapping = aes(x = Population,
                                               y = Barriers,
                                               fill = 100*Prop.Averted)) +
    geom_tile() +
    xlab(label = "Population") +
    ylab(label="Barrier lowered") +
    facet_grid(~ Tool, scales = "free_x", space = "free_x")+
    scale_fill_gradient(name = "% averted",
                      low = low.col,
                      high = high.col) +
    theme(text=element_text(size=12)) +
    scale_y_discrete(limits = rev(levels(as.factor(m$Barriers)))) # reverse the barrier ordering (so all barriers at the top).

